const Character = require("../character");

const characterSeeder = [ Character, [
    {
        "name": "Luke Skywalker", 
        "height": "172", 
        "mass": "77", 
        "hair_color": "blond", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "19BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 1, 2, 3, 6 ], 
        "species": [], 
        "vehicles": [ 14, 30 ], 
        "starships": [ 12, 22 ], 
        "created": "2014-12-09T13:50:51.644000Z", 
        "edited": "2014-12-20T21:17:56.891000Z", 
        "image": "luke-skywalker.jpg",
        "url": 1,
        "description" : "Luke Skywalker was a Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known. Along with his friends Princess Leia and Han Solo, Luke battled the evil Empire, discovered the truth of his parentage, and ended the tyranny of the Sith. A generation later, the location of the famed Jedi master was one of the galaxy’s greatest mysteries. Haunted by Ben Solo’s fall to evil and convinced the Jedi had to end, Luke sought exile on a distant world, ignoring the galaxy’s pleas for help. But his solitude would be interrupted – and Luke Skywalker had one final, momentous role to play in the struggle between good and evil."
    }, 
    {
        "name": "C-3PO", 
        "height": "167", 
        "mass": "75", 
        "hair_color": "n/a", 
        "skin_color": "gold", 
        "eye_color": "yellow", 
        "birth_year": "112BBY", 
        "gender": "n/a", 
        "homeworld": 1, 
        "films": [ 1, 2, 3, 4, 5, 6 ], 
        "species": [ 2 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T15:10:51.357000Z", 
        "edited": "2014-12-20T21:17:50.309000Z", 
        "image": "c-3po.jpg",
        "url": 2,
        "description" : "C-3PO longs for more peaceful times, but his continued service to the Resistance — and his knowledge of more than seven million forms of communication — keeps the worry-prone droid in the frontlines of galactic conflict. Programmed for etiquette and protocol, Threepio was built by a young Anakin Skywalker, and has been a constant companion to astromech R2-D2. Over the years, he was involved in some of the galaxy’s most defining moments and thrilling battles. Since the Empire’s defeat, C-3PO has served Leia Organa, head of a Resistance spy ring aimed at undermining the First Order."
    }, 
    {
        "name": "R2-D2", 
        "height": "96", 
        "mass": "32", 
        "hair_color": "n/a", 
        "skin_color": "white, blue", 
        "eye_color": "red", 
        "birth_year": "33BBY", 
        "gender": "n/a", 
        "homeworld": 8, 
        "films": [ 1, 2, 3, 4, 5, 6 ], 
        "species": [ 2 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T15:11:50.376000Z", 
        "edited": "2014-12-20T21:17:50.311000Z", 
        "image": "r2-d2.jpg",
        "url": 3,
        "description" : "A reliable and versatile astromech droid, R2-D2 has served Padmé Amidala, Anakin Skywalker, and Luke Skywalker in turn, showing great bravery in rescuing his masters and their friends from many perils. A skilled starship mechanic and fighter pilot's assistant, he has an unlikely but enduring friendship with the fussy protocol droid C-3PO."
    }, 
    {
        "name": "Darth Vader", 
        "height": "202", 
        "mass": "136", 
        "hair_color": "none", 
        "skin_color": "white", 
        "eye_color": "yellow", 
        "birth_year": "41.9BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 1, 2, 3, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 13 ], 
        "created": "2014-12-10T15:18:20.704000Z", 
        "edited": "2014-12-20T21:17:50.313000Z", 
        "image": "darth-vader.jpg",
        "url": 4,
        "description" : "Once a heroic Jedi Knight, Darth Vader was seduced by the dark side of the Force, became a Sith Lord, and led the Empire’s eradication of the Jedi Order. He remained in service of the Emperor -- the evil Darth Sidious -- for decades, enforcing his Master’s will and seeking to crush the fledgling Rebel Alliance. But there was still good in him…"
    }, 
    {
        "name": "Leia Organa", 
        "height": "150", 
        "mass": "49", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "19BBY", 
        "gender": "female", 
        "homeworld": 2, 
        "films": [ 1, 2, 3, 6 ], 
        "species": [], 
        "vehicles": [ 30 ], 
        "starships": [], 
        "created": "2014-12-10T15:20:09.791000Z", 
        "edited": "2014-12-20T21:17:50.315000Z", 
        "image": "leia.jpg",
        "url": 5,
        "description" : "Princess Leia Organa was one of the greatest leaders of the Rebel Alliance, fearless on the battlefield and dedicated to ending the Empire’s tyranny. Daughter of Padmé Amidala and Anakin Skywalker, sister of Luke Skywalker, and with a soft spot for scoundrels, Leia ranked among the galaxy’s great heroes. But life under the New Republic proved difficult for her. Sidelined by a new generation of political leaders, she struck out on her own to oppose the First Order as founder of the Resistance. These setbacks in her political career were accompanied by more personal losses, which she endured with her seemingly inexhaustible will."
    }, 
    {
        "name": "Owen Lars", 
        "height": "178", 
        "mass": "120", 
        "hair_color": "brown, grey", 
        "skin_color": "light", 
        "eye_color": "blue", 
        "birth_year": "52BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 1, 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T15:52:14.024000Z", 
        "edited": "2014-12-20T21:17:50.317000Z", 
        "image": "owen.jpg",
        "url": 6,
        "description" : "Owen Lars continued his father Cliegg’s efforts to build his homestead into a productive farm, working alongside his wife, Beru. Helping with the dreary chores required to keep the farm profitable, Owen relied on his nephew Luke Skywalker. He could not rein in Luke's drive for adventure, though. Young Skywalker longed to leave Tatooine and join the Imperial Academy, to live life among the stars. Owen forbade it, reminding Luke that he was needed on the moisture farm. Skywalker would eventually leave the farm, but under tragic circumstances. Imperials searching for missing droids razed the Lars homestead and killed Owen and Beru."
    }, 
    {
        "name": "Beru Whitesun lars", 
        "height": "165", 
        "mass": "75", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "blue", 
        "birth_year": "47BBY", 
        "gender": "female", 
        "homeworld": 1, 
        "films": [ 1, 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T15:53:41.121000Z", 
        "edited": "2014-12-20T21:17:50.319000Z", 
        "image": "beru.png",
        "url": 7,
        "description" : "As a young, shy girl, Beru Whitesun's aspirations did not reach beyond Tatooine. She was content to marry Owen Lars and lead the tough life of a moisture farmer. Beru also fulfilled the role of guardian and substitute mother to young Luke Skywalker, and repeatedly voiced her support for his dream of joining his friends at the Academy. Beru fell victim to the Empire when Imperial stormtroopers raided the family farm in search of droids thought to have top-secret plans for the Empire's ultimate weapon, the Death Star."
    }, 
    {
        "name": "R5-D4", 
        "height": "97", 
        "mass": "32", 
        "hair_color": "n/a", 
        "skin_color": "white, red", 
        "eye_color": "red", 
        "birth_year": "unknown", 
        "gender": "n/a", 
        "homeworld": 1, 
        "films": [ 1 ], 
        "species": [ 2 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T15:57:50.959000Z", 
        "edited": "2014-12-20T21:17:50.321000Z", 
        "image": "r5.jpg",
        "url": 8,
        "description" : "A red astromech droid, R5-D4 thought he'd found a home when the Jawas sold him to Owen Lars, along with the protocol droid C-3PO. But R5's motivator blew as he rolled away from the sandcrawler, forcing the Jawas to take him back in exchange for R2-D2."
    }, 
    {
        "name": "Biggs Darklighter", 
        "height": "183", 
        "mass": "84", 
        "hair_color": "black", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "24BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 1 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 12 ], 
        "created": "2014-12-10T15:59:50.509000Z", 
        "edited": "2014-12-20T21:17:50.323000Z", 
        "image": "biggs.jpg",
        "url": 9,
        "description" : "Biggs Darklighter grew up on Tatooine with Luke Skywalker, and shared his friend's dreams of escaping the dull desert world. After graduating from the Imperial Academy, he defected from the Empire's service to join the Rebellion. He and Luke were reunited at Yavin 4's Rebel base, and flew together against the Death Star. Luke returned from that mission as a hero, but Biggs did not survive."
    }, 
    {
        "name": "Obi-Wan Kenobi", 
        "height": "182", 
        "mass": "77", 
        "hair_color": "auburn, white", 
        "skin_color": "fair", 
        "eye_color": "blue-gray", 
        "birth_year": "57BBY", 
        "gender": "male", 
        "homeworld": 20, 
        "films": [ 1, 2, 3, 4, 5, 6 ], 
        "species": [], 
        "vehicles": [ 38 ], 
        "starships": [ 48, 59, 64, 65, 74 ], 
        "created": "2014-12-10T16:16:29.192000Z", 
        "edited": "2014-12-20T21:17:50.325000Z", 
        "image": "obi-wan-kenobi.jpg",
        "url": 10,
        "description" : "A legendary Jedi Master, Obi-Wan Kenobi was a noble man and gifted in the ways of the Force. He trained Anakin Skywalker, served as a general in the Republic Army during the Clone Wars, and guided Luke Skywalker as a mentor."
    },
    {
        "name": "Anakin Skywalker", 
        "height": "188", 
        "mass": "84", 
        "hair_color": "blond", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "41.9BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 4, 5, 6 ], 
        "species": [], 
        "vehicles": [ 44, 46 ], 
        "starships": [ 39, 59, 65 ], 
        "created": "2014-12-10T16:20:44.310000Z", 
        "edited": "2014-12-20T21:17:50.327000Z", 
        "image": "anakin-skywalker.jpg",
        "url": 11,
        "description" : "Discovered as a slave on Tatooine by Qui-Gon Jinn and Obi-Wan Kenobi, Anakin Skywalker had the potential to become one of the most powerful Jedi ever, and was believed by some to be the prophesied Chosen One who would bring balance to the Force. A hero of the Clone Wars, Anakin was caring and compassionate, but also had a fear of loss that would prove to be his downfall."
    }, 
    {
        "name": "Wilhuff Tarkin", 
        "height": "180", 
        "mass": "unknown", 
        "hair_color": "auburn, grey", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "64BBY", 
        "gender": "male", 
        "homeworld": 21, 
        "films": [ 1, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T16:26:56.138000Z", 
        "edited": "2014-12-20T21:17:50.330000Z", 
        "image": "tarkin.jpg",
        "url": 12,
        "description" : "An ambitious, ruthless proponent of military power, Wilhuff Tarkin became a favorite of Supreme Chancellor Palpatine and rose rapidly through the Imperial ranks. Shortly after the Empire's creation, he was put in charge of the construction of the Death Star. Tarkin saw the Death Star as a way to crush all dissent to the Empire's rule -- fear of the station's planet-killing superlaser would keep the galaxy's star systems in line. He demonstrated the station's power by destroying Alderaan, but died soon afterwards when the Death Star itself was destroyed."
    }, 
    {
        "name": "Chewbacca", 
        "height": "228", 
        "mass": "112", 
        "hair_color": "brown", 
        "skin_color": "unknown", 
        "eye_color": "blue", 
        "birth_year": "200BBY", 
        "gender": "male", 
        "homeworld": 14, 
        "films": [ 1, 2, 3, 6 ], 
        "species": [ 3 ], 
        "vehicles": [ 19 ], 
        "starships": [ 10, 22 ], 
        "created": "2014-12-10T16:42:45.066000Z", 
        "edited": "2014-12-20T21:17:50.332000Z", 
        "image": "chewbacca.jpg",
        "url": 13,
        "description" : "A legendary Wookiee warrior and Han Solo’s longtime co-pilot, Chewbacca continues to serve as faithful first mate to carry out daring missions against the First Order behind the controls of the Millennium Falcon. Known as Chewie to his closest friends, he was part of a core group of rebels who restored freedom to the galaxy during the reign of the Galactic Empire. Known for his short temper and accuracy with a bowcaster, Chewie also has a big heart and unwavering loyalty to his friends."
    }, 
    {
        "name": "Han Solo", 
        "height": "180", 
        "mass": "80", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "brown", 
        "birth_year": "29BBY", 
        "gender": "male", 
        "homeworld": 22, 
        "films": [ 1, 2, 3 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 10, 22 ], 
        "created": "2014-12-10T16:49:14.582000Z", 
        "edited": "2014-12-20T21:17:50.334000Z", 
        "image": "han-solo.jpg",
        "url": 14,
        "description" : "Han Solo rose from an impoverished childhood on the mean streets of Corellia to become one of the heroes of the Rebel Alliance. As captain of the Millennium Falcon, Han and his co-pilot Chewbacca came to believe in the cause of galactic freedom, joining Luke Skywalker and Princess Leia Organa in the fight against the Empire. After the Battle of Endor, Han faced difficult times in a chaotic galaxy, leading to a shattering confrontation with his estranged son Ben."
    }, 
    {
        "name": "Greedo", 
        "height": "173", 
        "mass": "74", 
        "hair_color": "n/a", 
        "skin_color": "green", 
        "eye_color": "black", 
        "birth_year": "44BBY", 
        "gender": "male", 
        "homeworld": 23, 
        "films": [ 1 ], 
        "species": [ 4 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T17:03:30.334000Z", 
        "edited": "2014-12-20T21:17:50.336000Z", 
        "image": "greedo.jpg",
        "url": 15,
        "description" : "Greedo was a Rodian bounty hunter with a tapir-like snout, bulbous eyes, pea-green skin, and a crest of spines atop his skull. He was overzealous and a bit slow on the take, not to mention a pretty poor shot with a blaster. Though he fancied himself a big time bounty hunter in the employ of no less an underworld figure than Jabba the Hutt, in truth, no one took him too seriously."
    }, 
    {
        "name": "Jabba Desilijic Tiure", 
        "height": "175", 
        "mass": "1,358", 
        "hair_color": "n/a", 
        "skin_color": "green-tan, brown", 
        "eye_color": "orange", 
        "birth_year": "600BBY", 
        "gender": "hermaphrodite", 
        "homeworld": 24, 
        "films": [ 1, 3, 4 ], 
        "species": [ 5 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-10T17:11:31.638000Z", 
        "edited": "2014-12-20T21:17:50.338000Z", 
        "image": "jabba-the-hutt.jpg",
        "url": 16,
        "description" : "Jabba the Hutt was one of the galaxy’s most powerful gangsters, with far-reaching influence in both politics and the criminal underworld. There were no second chances with Jabba, something Han Solo would find out -- though the slug-like alien would ultimately fall victim to his own hubris and vengeful ways."
    }, 
    {
        "name": "Wedge Antilles", 
        "height": "170", 
        "mass": "77", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "hazel", 
        "birth_year": "21BBY", 
        "gender": "male", 
        "homeworld": 22, 
        "films": [ 1, 2, 3 ], 
        "species": [], 
        "vehicles": [ 14 ], 
        "starships": [ 12 ], 
        "created": "2014-12-12T11:08:06.469000Z", 
        "edited": "2014-12-20T21:17:50.341000Z", 
        "image": "wedge-antilles.jpg",
        "url": 18,
        "description" : "A talented young rebel pilot from Corellia, Wedge Antilles survived the attack on the first Death Star to become a respected veteran of Rogue Squadron. He piloted a snowspeeder in the defense of Echo Base on Hoth, and led Red Squadron in the rebel attack on the second Death Star above Endor."
    }, 
    {
        "name": "Jek Tono Porkins", 
        "height": "180", 
        "mass": "110", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 26, 
        "films": [ 1 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 12 ], 
        "created": "2014-12-12T11:16:56.569000Z", 
        "edited": "2014-12-20T21:17:50.343000Z", 
        "image": "jek-tono-porkins.jpg",
        "url": 19,
        "description" : "Jek Porkins was a pilot and trader who abandoned his homeworld when the Empire moved in and developed a new military base there. The burly rebel pilot flew an X-wing at the Battle of Yavin under the call sign Red 6. His X-wing developed a mechanical problem early in the battle, leaving him struggling to maneuver. Before Porkins or his astromech could fix the problem, one of the Death Star’s turbolasers zeroed in on the X-wing, incinerating it and killing Porkins instantly."
    }, 
    {
        "name": "Yoda", 
        "height": "66", 
        "mass": "17", 
        "hair_color": "white", 
        "skin_color": "green", 
        "eye_color": "brown", 
        "birth_year": "896BBY", 
        "gender": "male", 
        "homeworld": 28, 
        "films": [ 2, 3, 4, 5, 6 ], 
        "species": [ 6 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-15T12:26:01.042000Z", 
        "edited": "2014-12-20T21:17:50.345000Z", 
        "image": "yoda.jpg",
        "url": 20,
        "description" : "Yoda was a legendary Jedi Master and stronger than most in his connection with the Force. Small in size but wise and powerful, he trained Jedi for over 800 years, playing integral roles in the Clone Wars, the instruction of Luke Skywalker, and unlocking the path to immortality."
    }, 
    {
        "name": "Palpatine", 
        "height": "170", 
        "mass": "75", 
        "hair_color": "grey", 
        "skin_color": "pale", 
        "eye_color": "yellow", 
        "birth_year": "82BBY", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 2, 3, 4, 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-15T12:48:05.971000Z", 
        "edited": "2014-12-20T21:17:50.347000Z", 
        "image": "palpatine.jpg",
        "url": 21,
        "description" : "The dark side of the Force is a pathway to many abilities some consider to be unnatural, and Sheev Palpatine is the most infamous follower of its doctrines. Scheming, powerful, and evil to the core, Darth Sidious restored the Sith and destroyed the Jedi Order. Living a double life, he was also Palpatine, a Naboo Senator and phantom menace. He manipulated the political system of the Galactic Republic until he was named Supreme Chancellor -- and eventually Emperor – and ruled the galaxy through fear and tyranny. The galaxy rejoiced when he died at the Battle of Endor, but Sidious had cheated death and patiently plotted a return to power."
    },
    {
        "name": "Boba Fett", 
        "height": "183", 
        "mass": "78.2", 
        "hair_color": "black", 
        "skin_color": "fair", 
        "eye_color": "brown", 
        "birth_year": "31.5BBY", 
        "gender": "male", 
        "homeworld": 10, 
        "films": [ 2, 3, 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 21 ], 
        "created": "2014-12-15T12:49:32.457000Z", 
        "edited": "2014-12-20T21:17:50.349000Z", 
        "image": "boba-fett.jpeg",
        "url": 22,
        "description" : "With his customized Mandalorian armor, deadly weaponry, and silent demeanor, Boba Fett was one of the most feared bounty hunters in the galaxy. A genetic clone of his “father,” bounty hunter Jango Fett, Boba learned combat and martial skills from a young age. Over the course of his career, which included contracts for the Empire and the criminal underworld, he became a legend."
    }, 
    {
        "name": "IG-88", 
        "height": "200", 
        "mass": "140", 
        "hair_color": "none", 
        "skin_color": "metal", 
        "eye_color": "red", 
        "birth_year": "15BBY", 
        "gender": "none", 
        "homeworld": 28, 
        "films": [ 2 ], 
        "species": [ 2 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-15T12:51:10.076000Z", 
        "edited": "2014-12-20T21:17:50.351000Z", 
        "image": "ig-88.jpeg",
        "url": 23,
        "description" : "Many people in the galaxy fear droids, what with the memories of the Clone Wars still fresh in their minds. Far more terrifying than battle droids were assassin droids, independently programmed mechanical killers that had no masters. IG-88 is a battered chrome war droid who has become a bounty hunter, and answered Darth Vader's call to capture the Millennium Falcon during the events surrounding the Battle of Hoth."
    }, 
    {
        "name": "Bossk", 
        "height": "190", 
        "mass": "113", 
        "hair_color": "none", 
        "skin_color": "green", 
        "eye_color": "red", 
        "birth_year": "53BBY", 
        "gender": "male", 
        "homeworld": 29, 
        "films": [ 2 ], 
        "species": [ 7 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-15T12:53:49.297000Z", 
        "edited": "2014-12-20T21:17:50.355000Z", 
        "image": "bossk.jpg",
        "url": 24,
        "description" : "One of the most feared bounty hunters of the galaxy, Bossk used his natural Trandoshan hunting instincts to capture his prey. During the Clone Wars, the red-eyed reptilian partnered with Aurra Sing, Castas and young Boba Fett. Bossk didn't care much for vendettas or politics. He was in it to get paid. After a brief stint in a Republic prison, Bossk continued his partnership with Fett, becoming a bodyguard to the teen bounty hunter. Decades later, Bossk answered Darth Vader's call to capture the Millennium Falcon after the Battle of Hoth, an assignment that put him in direct competition with Boba."
    }, 
    {
        "name": "Lando Calrissian", 
        "height": "177", 
        "mass": "79", 
        "hair_color": "black", 
        "skin_color": "dark", 
        "eye_color": "brown", 
        "birth_year": "31BBY", 
        "gender": "male", 
        "homeworld": 30, 
        "films": [ 2, 3 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 10 ], 
        "created": "2014-12-15T12:56:32.683000Z", 
        "edited": "2014-12-20T21:17:50.357000Z", 
        "image": "lando-calrissian.jpg",
        "url": 25,
        "description" : "Lando Calrissian may have come late to the fight against the Empire, but his role in destroying the second Death Star cemented his reputation as a hero. In his youth, Lando was a sportsman seeking a fortune at the sabacc tables. After he lost his beloved ship to Han Solo, Lando spent years living the high life and pursuing get-rich-quick schemes, with uneven results. He went semi-respectable as the baron administrator of Cloud City, only to be drawn into the fight against the Empire. After a personal tragedy, Lando sought solace in isolation on Pasaana, unaware that the galaxy would need him again."
    }, 
    {
        "name": "Lobot", 
        "height": "175", 
        "mass": "79", 
        "hair_color": "none", 
        "skin_color": "light", 
        "eye_color": "blue", 
        "birth_year": "37BBY", 
        "gender": "male", 
        "homeworld": 6, 
        "films": [ 2 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-15T13:01:57.178000Z", 
        "edited": "2014-12-20T21:17:50.359000Z", 
        "image": "lobot.jpg",
        "url": 26,
        "description" : "Never far from Baron Administrator Lando Calrissian's side was Lobot, Calrissian's aide and Cloud City's computer liaison officer. Lobot is a human male with a shiny, brain-enhancing device wrapped around the back of his skull that allowed him to contact directly with the city's central computer."
    }, 
    {
        "name": "Ackbar", 
        "height": "180", 
        "mass": "83", 
        "hair_color": "none", 
        "skin_color": "brown mottle", 
        "eye_color": "orange", 
        "birth_year": "41BBY", 
        "gender": "male", 
        "homeworld": 31, 
        "films": [ 3 ], 
        "species": [ 8 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-18T11:07:50.584000Z", 
        "edited": "2014-12-20T21:17:50.362000Z", 
        "image": "ackbar.jpg",
        "url": 27,
        "description" : "A veteran commander, Ackbar led the defense of his homeworld, Mon Cala, during the Clone Wars and then masterminded the rebel attack on the second Death Star at the Battle of Endor. Ackbar realized the rebels had been drawn into a trap at Endor, but adjusted, with his fleet buying valuable time for the attack to succeed. After the Battle of Endor, Ackbar became a Grand Admiral in the New Republic, winning many victories including the pivotal Battle of Jakku. He retired to Mon Cala, but was coaxed back into service with the Resistance by Leia Organa."
    }, 
    {
        "name": "Mon Mothma", 
        "height": "150", 
        "mass": "unknown", 
        "hair_color": "auburn", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "48BBY", 
        "gender": "female", 
        "homeworld": 32, 
        "films": [ 3 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-18T11:12:38.895000Z", 
        "edited": "2014-12-20T21:17:50.364000Z", 
        "image": "mon-mothma.jpg",
        "url": 28,
        "description" : "A leader of the Galactic Senate's Loyalist faction, Mon Mothma opposed Supreme Chancellor Palpatine's policies during the final days of the Republic. Working in secret, she helped found the Rebel Alliance, and served as its civilian leader during the long struggle against the Empire."
    }, 
    {
        "name": "Arvel Crynyd", 
        "height": "unknown", 
        "mass": "unknown", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 28, 
        "films": [ 3 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 28 ], 
        "created": "2014-12-18T11:16:33.020000Z", 
        "edited": "2014-12-20T21:17:50.367000Z", 
        "image": "arvel-crynyd.jpg",
        "url": 29,
        "description" : "Arvel Crynyd fue un humano piloto que sirvió a la Alianza para Restaurar la República durante la Guerra Civil Galáctica. En el 4 DBY, Crynyd participó en el asalto de la Alianza en la segunda Estrella de la Muerte del Imperio Galáctico en la Batalla de Endor, volando un interceptor RZ-1 Ala-A como líder del Escuadrón Verde."
    }, 
    {
        "name": "Wicket Systri Warrick", 
        "height": "88", 
        "mass": "20", 
        "hair_color": "brown", 
        "skin_color": "brown", 
        "eye_color": "brown", 
        "birth_year": "8BBY", 
        "gender": "male", 
        "homeworld": 7, 
        "films": [ 3 ], 
        "species": [ 9 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-18T11:21:58.954000Z", 
        "edited": "2014-12-20T21:17:50.369000Z", 
        "image": "wicket-systri-warrick.png",
        "url": 30,
        "description" : "Wicket W. Warrick was the brave young Ewok who willingly joined the Rebellion and aided in the battle against the Empire on the forest moon of Endor. Even before he encountered the Rebels, Wicket had devised methods for defeating the Imperial machines, plans which were implemented after the Ewok befriended Princess Leia and recruited his tribe to the Alliance's cause. During the Battle of Endor, Wicket fought valiantly alongside his new allies."
    }, 
    {
        "name": "Nien Nunb", 
        "height": "160", 
        "mass": "68", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 33, 
        "films": [ 3 ], 
        "species": [ 10 ], 
        "vehicles": [], 
        "starships": [ 10 ], 
        "created": "2014-12-18T11:26:18.541000Z", 
        "edited": "2014-12-20T21:17:50.371000Z", 
        "image": "nien-nunb.jpg",
        "url": 31,
        "description" : "A native of Sullust, Nien Nunb was a smuggler who fought for both the Rebel Alliance and the Resistance during his long career. An expert pilot, he served as Lando Calrissian’s co-pilot aboard the Millennium Falcon during the Battle of Endor, flew an X-wing in the raid on Starkiller Base and survived the First Order’s assault on Crait. He was then killed fighting for freedom at Exegol."
    },
    {
        "name": "Qui-Gon Jinn", 
        "height": "193", 
        "mass": "89", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "92BBY", 
        "gender": "male", 
        "homeworld": 28, 
        "films": [ 4 ], 
        "species": [], 
        "vehicles": [ 38 ], 
        "starships": [], 
        "created": "2014-12-19T16:54:53.618000Z", 
        "edited": "2014-12-20T21:17:50.375000Z", 
        "image": "qui-gon-jinn.jpg",
        "url": 32,
        "description" : "A venerable if maverick Jedi Master, Qui-Gon Jinn was a student of the living Force. Qui-Gon lived for the moment, espousing a philosophy of feel, don't think -- use your instincts. On Tatooine, Qui-Gon discovered a young slave boy named Anakin Skywalker who was strong in the Force. Sensing the boys potential, Qui-Gon liberated Anakin from slavery. The Jedi Master presented Anakin to the Jedi Council, but they deemed the boy too old to begin training and dangerously full of fear and anger. They refused to allow Qui-Gon to train Anakin, but rescinded their decision to fulfill Qui-Gons dying wish. "
    }, 
    {
        "name": "Nute Gunray", 
        "height": "191", 
        "mass": "90", 
        "hair_color": "none", 
        "skin_color": "mottled green", 
        "eye_color": "red", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 18, 
        "films": [ 4, 5, 6 ], 
        "species": [ 11 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:05:57.357000Z", 
        "edited": "2014-12-20T21:17:50.377000Z", 
        "image": "nute-gunray.jpg",
        "url": 33,
        "description" : "Neimoidians are known for their business skills, but Nute Gunray, Viceroy of the Trade Federation, was more cutthroat than most. It was Gunray who conspired with the Sith Lord Darth Sidious to launch the blockade and subsequent invasion of Naboo. Once the planet was under siege, Gunray attempted to force Queen Amidala to sign a treaty that would legitimize the occupation. Amidala escaped, and returned to infiltrate her own palace and blast through Gunray's protectors. Arrested by Republic officials, Gunray was carted off to answer for his crimes, but evaded imprisonment and kept his post."
    }, 
    {
        "name": "Finis Valorum", 
        "height": "170", 
        "mass": "unknown", 
        "hair_color": "blond", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "91BBY", 
        "gender": "male", 
        "homeworld": 9, 
        "films": [ 4 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:21:45.915000Z", 
        "edited": "2014-12-20T21:17:50.379000Z", 
        "image": "finis-valorum.jpg",
        "url": 34,
        "description" : "A well-meaning civil servant whose chancellorship was hampered by corruption in the Senate and bureaucratic snarls, Valorum secretly turned to the Jedi Knights for help breaking the Trade Federation's blockade of Naboo. But Valorum was betrayed by Naboo's Senator Palpatine, who maneuvered Queen Amidala into asking the Senate for a no-confidence vote in the Supreme Chancellor's leadership. A stunned Valorum was removed from office in favor of Palpatine."
    }, 
    {
        "name": "Padmé Amidala", 
        "height": "185", 
        "mass": "45", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "46BBY", 
        "gender": "female", 
        "homeworld": 8, 
        "films": [ 4, 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 39, 49, 64 ], 
        "created": "2014-12-19T17:28:26.926000Z", 
        "edited": "2014-12-20T21:17:50.381000Z", 
        "image": "padme-amidala.jpg",
        "url": 35,
        "description" : "Padmé Amidala was a courageous, hopeful leader, serving as Queen and then Senator of Naboo -- and was also handy with a blaster. Despite her ideals and all she did for the cause of peace, her secret, forbidden marriage to Jedi Anakin Skywalker would prove to have dire consequences for the galaxy."
    }, 
    {
        "name": "Jar Jar Binks", 
        "height": "196", 
        "mass": "66", 
        "hair_color": "none", 
        "skin_color": "orange", 
        "eye_color": "orange", 
        "birth_year": "52BBY", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 4, 5 ], 
        "species": [ 12 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:29:32.489000Z", 
        "edited": "2014-12-20T21:17:50.383000Z", 
        "image": "jar-jar-binks.jpg",
        "url": 36,
        "description" : "A clumsy, well-meaning Gungan outcast on Naboo, Jar Jar Binks struggled to prove his worth throughout his life. Putting his awkward past behind him, Jar Jar left the swamps of Naboo to enter the even murkier waters of Coruscant politics, becoming a representative for his people in the galactic capital. There, his best intentions and eagerness to serve were exploited by scheming Senators and others in positions of power."
    }, 
    {
        "name": "Roos Tarpals", 
        "height": "224", 
        "mass": "82", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "orange", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 4 ], 
        "species": [ 12 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:32:56.741000Z", 
        "edited": "2014-12-20T21:17:50.385000Z", 
        "image": "roos-tarpals.jpg",
        "url": 37,
        "description" : "The gravelly-voiced patrol chief of Otoh Gunga, Tarpals has endured many a headache caused by the antics of Jar Jar Binks. Tarpals kept an eye on the bumbling outcast, making sure the youngster didn't re-enter Gungan society. During the Trade Federation occupation of Naboo, Tarpals was part of the Gungan Grand Army that fought against the battle droid invaders. Ironically, Tarpals served under Binks, who had unexpectedly received the rank of general by Boss Nass himself. Tarpals stayed close to Binks, trying to keep his commanding officer out of trouble. By the time of the Clone Wars, Tarpals was promoted to general, and served as leader of the Gungan Grand Army."
    }, 
    {
        "name": "Rugor Nass", 
        "height": "206", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "green", 
        "eye_color": "orange", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 4 ], 
        "species": [ 12 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:33:38.909000Z", 
        "edited": "2014-12-20T21:17:50.388000Z", 
        "image": "rugor-nass.jpg",
        "url": 38,
        "description" : "The stout and stern leader of the Gungans, Boss Nass was a proud keeper of his people's ways. His booming voice issued decrees on behalf of all the Gungans of Otoh Gunga. He kept a tight rein on Gungan affairs, continuing a longstanding custom of isolationism. Though Nass' temper is short, displays of courage and humility can pierce through his preconceptions. When Queen Amidala prostrated herself before the Gungan leader to request his aid in fighting off the Trade Federation invasion, he was impressed. Nass committed the Gungan Grand Army to wage war against invading battle droids."
    }, 
    {
        "name": "Ric Olié", 
        "height": "183", 
        "mass": "unknown", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 4 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 40 ], 
        "created": "2014-12-19T17:45:01.522000Z", 
        "edited": "2014-12-20T21:17:50.392000Z", 
        "image": "ric-olie.jpg",
        "url": 39,
        "description" : "A veteran of the Naboo Space Fighter Corps, Ric Olie was the leader of Bravo Flight and had the honor of flying Queen Amidala's Royal Starship to and from Naboo. Answerable directly to Captain Panaka, Olie was capable of flying any craft on Naboo. During the Battle of Naboo, Olie's squadron of N-1 starfighters were successful in destroying the Trade Federation's Droid Control Ship with the help of Anakin Skywalker."
    }, 
    {
        "name": "Watto", 
        "height": "137", 
        "mass": "unknown", 
        "hair_color": "black", 
        "skin_color": "blue, grey", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 34, 
        "films": [ 4, 5 ], 
        "species": [ 13 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:48:54.647000Z", 
        "edited": "2014-12-20T21:17:50.395000Z", 
        "image": "watto.jpg",
        "url": 40,
        "description" : "Watto was a Toydarian junk dealer in Mos Espa who bought Shmi Skywalker and her son Anakin from Gardulla the Hutt. An inveterate gambler, he sponsored Anakin in several Podraces, but often bet against his own slave, who was talented but inexperienced. Watto lost Anakin to Qui-Gon Jinn in a wager on the Boonta Eve race. Years later, he sold Shmi to the moisture farmer Cliegg Lars."
    }, 
    {
        "name": "Sebulba", 
        "height": "112", 
        "mass": "40", 
        "hair_color": "none", 
        "skin_color": "grey, red", 
        "eye_color": "orange", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 35, 
        "films": [ 4 ], 
        "species": [ 14 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:53:02.586000Z", 
        "edited": "2014-12-20T21:17:50.397000Z", 
        "image": "sebulba.jpg",
        "url": 41,
        "description" : "A crafty, vicious Dug, Sebulba became one of the Outer Rim's most successful Podracers. Whether roaming the streets of Mos Espa or piloting his massive orange Podracer, Sebulba was aggressive and arrogant. He was not above cheating to win a race, and would even resort to illegal weapons in an attempt to defeat his opponents. Sebulba was Mos Espa's reigning Podrace champion until he entered the Boonta Eve Classic, where he was defeated by young Anakin Skywalker, much to the Dug's frustration."
    },
    {
        "name": "Quarsh Panaka", 
        "height": "183", 
        "mass": "unknown", 
        "hair_color": "black", 
        "skin_color": "dark", 
        "eye_color": "brown", 
        "birth_year": "62BBY", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 4 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:55:43.348000Z", 
        "edited": "2014-12-20T21:17:50.399000Z", 
        "image": "quarsh-panaka.jpg",
        "url": 42,
        "description" : "Queen Amidala's loyal protector during the Trade Federation invasion crisis was Captain Panaka. Panaka was often referred to as the quickest eyes on Naboo for his attention to detail and selfless dedication to the safety of the Queen. Panaka commanded a team of Royal Palace Guards and Security Troopers stationed throughout Theed. During the Trade Federation invasion, Panaka stayed close to the Queen, ensuring her protection from the Neimoidians' plans. His loyalty was such that he would openly question the strategy of Jedi Knights if he thought it would somehow endanger Amidala."
    }, 
    {
        "name": "Shmi Skywalker", 
        "height": "163", 
        "mass": "unknown", 
        "hair_color": "black", 
        "skin_color": "fair", 
        "eye_color": "brown", 
        "birth_year": "72BBY", 
        "gender": "female", 
        "homeworld": 1, 
        "films": [ 4, 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-19T17:57:41.191000Z", 
        "edited": "2014-12-20T21:17:50.401000Z", 
        "image": "shmi-skywalker.jpg",
        "url": 43,
        "description" : "The mother of Anakin Skywalker was also a brave and resilient woman who survived life as a slave to become a Tatooine moisture farmer. Shmi surrendered her son to the Jedi Order, putting him on a path to become one of the greatest Jedi. Her death at the hands of Tusken Raiders became a critical step on Anakin's journey to the dark side."
    }, 
    {
        "name": "Darth Maul", 
        "height": "175", 
        "mass": "80", 
        "hair_color": "none", 
        "skin_color": "red", 
        "eye_color": "yellow", 
        "birth_year": "54BBY", 
        "gender": "male", 
        "homeworld": 36, 
        "films": [ 4 ], 
        "species": [ 22 ], 
        "vehicles": [ 42 ], 
        "starships": [ 41 ], 
        "created": "2014-12-19T18:00:41.929000Z", 
        "edited": "2014-12-20T21:17:50.403000Z", 
        "image": "darth-maul.png",
        "url": 44,
        "description" : "A deadly, agile Sith Lord trained by the evil Darth Sidious, Darth Maul was a formidable warrior and scheming mastermind. He wielded an intimidating double-bladed lightsaber and fought with a menacing ferocity. Though he fell in battle against Obi-Wan Kenobi, the Zabrak from Dathomir would prove to be much harder to destroy than originally believed."
    }, 
    {
        "name": "Bib Fortuna", 
        "height": "180", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "pale", 
        "eye_color": "pink", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 37, 
        "films": [ 3 ], 
        "species": [ 15 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T09:47:02.512000Z", 
        "edited": "2014-12-20T21:17:50.407000Z", 
        "image": "bib-fortuna.png",
        "url": 45,
        "description" : "Those attempting to do business with Jabba the Hutt first needed to maneuver past his pasty-faced majordomo, the Twi'lek Bib Fortuna. The darkly robed attendant often hovered near Jabba's ear, offering advice and feeding information. Fortuna followed the rules of protocol in the Hutt's court (such as they were), and spoke only in Huttese, though he understood other tongues. Fortuna's affiliation with Jabba stretched over decades."
    }, 
    {
        "name": "Ayla Secura", 
        "height": "178", 
        "mass": "55", 
        "hair_color": "none", 
        "skin_color": "blue", 
        "eye_color": "hazel", 
        "birth_year": "48BBY", 
        "gender": "female", 
        "homeworld": 37, 
        "films": [ 4, 5, 6 ], 
        "species": [ 15 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T09:48:01.172000Z", 
        "edited": "2014-12-20T21:17:50.409000Z", 
        "image": "ayla-secura.jpg",
        "url": 46,
        "description" : "With an athletic build, an exotic beauty, and blue skin, Aayla Secura stood out among the many faces of the Jedi ranks. A cunning warrior and Jedi Knight during the rise of the Clone Wars, Aayla fought alongside Clone Commander Bly on many exotic battlefields. Having mastered the emotional detachment necessary in the Jedi Order, she always tried to pass on what she had learned to others. Aayla was killed, along with many other Jedi Generals, when her troops turned on her in reaction to Supreme Chancellor Palpatine’s broadcast of Order 66."
    }, 
    {
        "name": "Ratts Tyerel", 
        "height": "79", 
        "mass": "15", 
        "hair_color": "none", 
        "skin_color": "grey, blue", 
        "eye_color": "unknown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 38, 
        "films": [ 4 ], 
        "species": [ 16 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T09:53:15.086000Z", 
        "edited": "2014-12-20T21:17:50.410000Z", 
        "image": "ratts-tyerel.jpg",
        "url": 47,
        "description" : "Ratts Tyerell was the tiniest of the Podracer pilots in the Boonta Eve Classic, though size matters not in such a competition. The little scrapper piloted a Podracer with immense engines ... too big, it would seem, for the tight confines of the Laguna Caves. On the second lap of the race, Ratts' accelerator jammed, and he couldn't get clearance past the rocky stalactites. The resulting fireball killed the little guy. His family, who had traveled to Mos Espa to witness the race, was reportedly seen grieving shortly thereafter."
    }, 
    {
        "name": "Dud Bolt", 
        "height": "94", 
        "mass": "45", 
        "hair_color": "none", 
        "skin_color": "blue, grey", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 39, 
        "films": [ 4 ], 
        "species": [ 17 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T09:57:31.858000Z", 
        "edited": "2014-12-20T21:17:50.414000Z", 
        "image": "dud-bolt.jpg",
        "url": 48,
        "description" : "Dud Bolt era un piloto de pods de carreras vulptereeno que era conocido por participar en el Clásico de Boonta Eve, prefiriendo el uso de un Pod de carreras Vulptereeno 327."
    }, 
    {
        "name": "Gasgano", 
        "height": "122", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "white, blue", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 40, 
        "films": [ 4 ], 
        "species": [ 18 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:02:12.223000Z", 
        "edited": "2014-12-20T21:17:50.416000Z", 
        "image": "gasgano.jpg",
        "url": 49,
        "description" : "A slight, spindly, six-limbed alien, Gasgano was a thrill-seeker uniquely suited to the extreme sport of Podracing. Gasgano was very competitive, and sought to beat racers Anakin Skywalker and Sebulba during the Boonta Eve Podrace. He piloted a green Ord Pedrovia Podracer in the competition."
    }, 
    {
        "name": "Ben Quadinaros", 
        "height": "163", 
        "mass": "65", 
        "hair_color": "none", 
        "skin_color": "grey, green, yellow", 
        "eye_color": "orange", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 41, 
        "films": [ 4 ], 
        "species": [ 19 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:08:33.777000Z", 
        "edited": "2014-12-20T21:17:50.417000Z", 
        "image": "ben-quadinaros.png",
        "url": 50,
        "description" : "The pudgy, comic-faced Ben Quadinaros was a rookie Podracer who claimed he came from the mysterious Tund system. He competed in the Boonta Eve Podrace that saw the liberation of Anakin Skywalker from slavery. Ben was largely inexperienced, and was quite terrified of the Boonta race. At the start of the race, his engines wouldn't even ignite. It was not until most of his competitors were already heading towards their second lap that his four engines did light -- just as his power couplings shorted, sending the rockets flying about the arena."
    }, 
    {
        "name": "Mace Windu", 
        "height": "188", 
        "mass": "84", 
        "hair_color": "none", 
        "skin_color": "dark", 
        "eye_color": "brown", 
        "birth_year": "72BBY", 
        "gender": "male", 
        "homeworld": 42, 
        "films": [ 4, 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:12:30.846000Z", 
        "edited": "2014-12-20T21:17:50.420000Z", 
        "image": "mace-windu.jpg",
        "url": 51,
        "description" : "A grim Jedi Master with an amethyst-bladed lightsaber, Mace Windu was the champion of the Jedi Order, with little tolerance for the failings of the Senate, the arguments of politicians, or the opinions of rebellious Jedi. As the Clone Wars intensified, Mace sensed the dark side of the Force at work, and knew the Jedi's enemies were plotting to destroy the Order and end its stewardship of the galaxy."
    },
    {
        "name": "Ki-Adi-Mundi", 
        "height": "198", 
        "mass": "82", 
        "hair_color": "white", 
        "skin_color": "pale", 
        "eye_color": "yellow", 
        "birth_year": "92BBY", 
        "gender": "male", 
        "homeworld": 43, 
        "films": [ 4, 5, 6 ], 
        "species": [ 20 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:15:32.293000Z", 
        "edited": "2014-12-20T21:17:50.422000Z", 
        "image": "ki-adi-mundi.jpg",
        "url": 52,
        "description" : "Ki-Adi-Mundi was a Cerean alien who sat on the Jedi Council. A humanoid being, Ki's most distinguishing physical feature was an enlarged conical cranium that contained a binary brain. When Jedi Master Qui-Gon Jinn reported a Sith attack during the events surrounding the Battle of Naboo, Ki-Adi-Mundi expressed shock at the notion. Impossible, he remarked, the Sith have been extinct for a millennium. He also failed to see how far Count Dooku had fallen from the Jedi ideals just prior to the Clone Wars, believing that Dooku was incapable of violence or murder."
    }, 
    {
        "name": "Kit Fisto", 
        "height": "196", 
        "mass": "87", 
        "hair_color": "none", 
        "skin_color": "green", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 44, 
        "films": [ 4, 5, 6 ], 
        "species": [ 21 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:18:57.202000Z", 
        "edited": "2014-12-20T21:17:50.424000Z", 
        "image": "kit-fisto.jpg",
        "url": 53,
        "description" : "Kit Fisto is a striking example of an alien Jedi, a Nautolan with large eyes, and a gathered tangle of flexible tentacle-tresses extending from his head. He is at home in the waters of aquatic planets, like his native Glee Anselm. As a Jedi Master, Fisto has an intense focus, particularly in combat. He is also much more laid back and capable of enjoying a hearty chuckle than some of his humorless colleagues."
    }, 
    {
        "name": "Eeth Koth", 
        "height": "171", 
        "mass": "unknown", 
        "hair_color": "black", 
        "skin_color": "brown", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 45, 
        "films": [ 4, 6 ], 
        "species": [ 22 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:26:47.902000Z", 
        "edited": "2014-12-20T21:17:50.427000Z", 
        "image": "eeth-koth.jpg",
        "url": 54,
        "description" : "Eeth Koth was a member of the Jedi High Council in the final years of the order. From within the polished towers of the Jedi Temple on Coruscant, the Council governed the actions of the Jedi Knights. Koth was one of the 12 Jedi present when Qui-Gon Jinn presented Anakin Skywalker as the Chosen One to the Council. A determined warrior with a deep, spiritual connection to the Force, Koth resisted torture at the hands of General Grievous during the Clone Wars, and was even able to secretly communicate his location to the Jedi Council. Koth was saved from Separatist clutches by the daring efforts of his fellow Jedi."
    }, 
    {
        "name": "Adi Gallia", 
        "height": "184", 
        "mass": "50", 
        "hair_color": "none", 
        "skin_color": "dark", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 9, 
        "films": [ 4, 6 ], 
        "species": [ 23 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:29:11.661000Z", 
        "edited": "2014-12-20T21:17:50.432000Z", 
        "image": "adi-gallia.jpg",
        "url": 55,
        "description" : "Jedi Master Adi Gallia was a member of the Order's High Council during the Clone Wars. She and the other members of that ruling body would convene in a temple high above the Coruscant landscape, deciding important matters of the Jedi. Stern and focused, she would remark upon the more outrageous tactics carried out by Anakin Skywalker or Obi-Wan Kenobi in the course of the war, but would rarely condemn their effective actions. Though not as brash as Anakin, Adi Gallia was known to be an aggressive warrior who had no problem bringing the fight to the enemy."
    }, 
    {
        "name": "Saesee Tiin", 
        "height": "188", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "pale", 
        "eye_color": "orange", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 47, 
        "films": [ 4, 6 ], 
        "species": [ 24 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:32:11.669000Z", 
        "edited": "2014-12-20T21:17:50.434000Z", 
        "image": "saesee-tiin.jpg",
        "url": 56,
        "description" : "The imposing Saesee Tiin was a member of the Jedi Council during the final years of the Republic. In addition to being a skilled, courageous master of the lightsaber, he was also a capable starfighter pilot. Tiin voyaged to Naboo to attend the funeral of fallen Jedi Qui-Gon Jinn, and the jubilant celebration that marked the liberation of that outlying world. Ten years after this event, Tiin was still an active member of the Jedi order, and a vital battlefield general in the Clone Wars."
    }, 
    {
        "name": "Yarael Poof", 
        "height": "264", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "white", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 48, 
        "films": [ 4 ], 
        "species": [ 25 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:34:48.725000Z", 
        "edited": "2014-12-20T21:17:50.437000Z", 
        "image": "yarael-poof.jpg",
        "url": 57,
        "description" : "A gaunt, long-necked Quermian, Yarael Poof had two brains and four arms, which he kept hidden beneath his Jedi robes. Poof was a member of the Jedi Council during the final years of the Republic, and was in the Jedi Council Chamber when Qui-Gon Jinn returned from Tatooine with the extraordinary news that the ancient Sith had returned to challenge the Jedi once more."
    }, 
    {
        "name": "Plo Koon", 
        "height": "188", 
        "mass": "80", 
        "hair_color": "none", 
        "skin_color": "orange", 
        "eye_color": "black", 
        "birth_year": "22BBY", 
        "gender": "male", 
        "homeworld": 49, 
        "films": [ 4, 5, 6 ], 
        "species": [ 26 ], 
        "vehicles": [], 
        "starships": [ 48 ], 
        "created": "2014-12-20T10:49:19.859000Z", 
        "edited": "2014-12-20T21:17:50.439000Z", 
        "image": "plo-koon.png",
        "url": 58,
        "description" : "A Kel Dor from Dorin, Plo Koon was among the wisest members of the Jedi Order, respected for his level-headed analysis of events and unflappable calm. Deeply concerned for life in all its myriad forms, Plo was especially devoted to protecting the clones under his command. He shared a special bond with Ahsoka Tano, whom he’d brought to the Jedi Order as a toddler. One of many victims of Order 66, Master Plo died at Cato Neimoidia when his wingmen shot down his starfighter."
    }, 
    {
        "name": "Mas Amedda", 
        "height": "196", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "blue", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 50, 
        "films": [ 4, 5 ], 
        "species": [ 27 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T10:53:26.457000Z", 
        "edited": "2014-12-20T21:17:50.442000Z", 
        "image": "mas-amedda.jpg",
        "url": 59,
        "description" : "Mas Amedda was the Vice Chair of the Galactic Senate during Chancellor Valorum's term, a position he continued to hold as Chancellor Palpatine transformed the Republic into the Galactic Empire. Amedda's booming voice often called for order when the partisan nature of the Republic's government degenerated into pointless bickering. In an alien gesture of authority, he would often punctuate such calls with a flicker of his long, forked tongue."
    }, 
    {
        "name": "Gregar Typho", 
        "height": "185", 
        "mass": "85", 
        "hair_color": "black", 
        "skin_color": "dark", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 8, 
        "films": [ 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [ 39 ], 
        "created": "2014-12-20T11:10:10.381000Z", 
        "edited": "2014-12-20T21:17:50.445000Z", 
        "image": "gregar-typho.png",
        "url": 60,
        "description" : "Gregar Typho succeeded Captain Panaka as head of Padmé Amidala’s security detail, protecting her as Naboo’s queen and then as its Senator. During the Separatist Crisis, Typho endorsed the plan for Padmé to evade assassins by secretly returning to Naboo with Anakin Skywalker. He loyally defended the Senator against a host of enemies in the Clone Wars."
    }, 
    {
        "name": "Cordé", 
        "height": "157", 
        "mass": "unknown", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 8, 
        "films": [ 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T11:11:39.630000Z", 
        "edited": "2014-12-20T21:17:50.449000Z", 
        "image": "corde.png",
        "url": 61,
        "description" : "Cordé, anteriormente conocida como Cordyn, fue una doncella humana que sirvió a la Senadora Padmé Amidala en los días previos a las Guerras Clon. Ella estaba actuando como un señuelo cuando fue asesinada en un atentado contra la vida de Amidala por la cazarrecompensas clawdite Zam Wesell."
    },
    {
        "name": "Cliegg Lars", 
        "height": "183", 
        "mass": "unknown", 
        "hair_color": "brown", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "82BBY", 
        "gender": "male", 
        "homeworld": 1, 
        "films": [ 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T15:59:03.958000Z", 
        "edited": "2014-12-20T21:17:50.451000Z", 
        "image": "cliegg-lars.jpg",
        "url": 62,
        "description" : "Cliegg Lars was a modest, good-hearted moisture farmer who lived on the Lars homestead, not far from the township of Anchorhead. During a trip to the bustling spaceport of Mos Espa, Cliegg fell in love with Shmi Skywalker, a slave owned by Toydarian junk trader Watto. Cliegg purchased Shmi's freedom and, soon after, made her his bride. They lived a quiet existence for years on the homestead, surviving against the harsh desert elements. With Owen, Cliegg's son from a previous union, and Owen's girlfriend Beru Whitesun, the Lars homestead was a tiny island of familial warmth amidst the endless desert wastes. Until tragedy struck..."
    }, 
    {
        "name": "Poggle the Lesser", 
        "height": "183", 
        "mass": "80", 
        "hair_color": "none", 
        "skin_color": "green", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 11, 
        "films": [ 5, 6 ], 
        "species": [ 28 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:40:43.977000Z", 
        "edited": "2014-12-20T21:17:50.453000Z", 
        "image": "poggle.jpg",
        "url": 63,
        "description" : "Poggle the Lesser was the leader of the insect-like Geonosians throughout the era of the Clone Wars. Due to his control of the Geonosian battle droid factories, he was a powerful figure within the Confederacy of Independent Systems and commanded the droid armies that fought against the Republic in two battles for control of Geonosis. At the end of the war, Poggle lost his life to Darth Vader."
    }, 
    {
        "name": "Luminara Unduli", 
        "height": "170", 
        "mass": "56.2", 
        "hair_color": "black", 
        "skin_color": "yellow", 
        "eye_color": "blue", 
        "birth_year": "58BBY", 
        "gender": "female", 
        "homeworld": 51, 
        "films": [ 5, 6 ], 
        "species": [ 29 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:45:53.668000Z", 
        "edited": "2014-12-20T21:17:50.455000Z", 
        "image": "luminara-unduli.jpg",
        "url": 64,
        "description" : "A green-skinned Mirialan, Luminara Unduli served the Jedi Order during the final years of the Galactic Republic, and trained the capable Padawan Barriss Offee. A no-nonsense Jedi Master, Luminara fought in Clone Wars battles such as Geonosis and Kashyyyk, and was thought to have perished during Order 66. In reality, she’d been taken into Imperial custody and executed, with holographic transmissions of her captivity used as bait to capture fugitive Jedi."
    }, 
    {
        "name": "Barriss Offee", 
        "height": "166", 
        "mass": "50", 
        "hair_color": "black", 
        "skin_color": "yellow", 
        "eye_color": "blue", 
        "birth_year": "40BBY", 
        "gender": "female", 
        "homeworld": 51, 
        "films": [ 5 ], 
        "species": [ 29 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:46:40.440000Z", 
        "edited": "2014-12-20T21:17:50.457000Z", 
        "image": "barriss-offee.jpg",
        "url": 65,
        "description" : "The Mirialan Padawan to Luminara Unduli, Barriss Offee preferred learning and studying ancient Jedi texts in the Temple to war. This mindset, while noble, led her down a dark path that saw her betray friends and commit terrible acts."
    }, 
    {
        "name": "Dormé", 
        "height": "165", 
        "mass": "unknown", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 8, 
        "films": [ 5 ], 
        "species": [ 1 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:49:14.640000Z", 
        "edited": "2014-12-20T21:17:50.460000Z", 
        "image": "dorme.jpg",
        "url": 66,
        "description" : "Despite no longer being Naboo’s queen, Padmé Amidala retained some royal perks as senator. Among them were her loyal handmaidens – a name that did little justice to the women’s training as bodyguards. Padmé’s most devoted aide, Dormé, advised the senator on Coruscant and helped look after Naboo’s affairs when Padmé retreated to her homeworld with Anakin Skywalker."
    }, 
    {
        "name": "Dooku", 
        "height": "193", 
        "mass": "80", 
        "hair_color": "white", 
        "skin_color": "fair", 
        "eye_color": "brown", 
        "birth_year": "102BBY", 
        "gender": "male", 
        "homeworld": 52, 
        "films": [ 5, 6 ], 
        "species": [ 1 ], 
        "vehicles": [ 55 ], 
        "starships": [], 
        "created": "2014-12-20T16:52:14.726000Z", 
        "edited": "2014-12-20T21:17:50.462000Z", 
        "image": "dooku.jpg",
        "url": 67,
        "description" : "Count Dooku was a menacing Sith Lord and central figure in the Clone Wars. Once a Jedi -- trained by Yoda -- he became disillusioned with the Jedi Order and thirsted for greater power. Dooku voluntarily left the light side behind and became Darth Sidious’ dark side disciple, taking the secret name Darth Tyranus and leading the Separatist army. Dooku advanced Sidious’s secret plot to take over the galaxy, but forgot that betrayal is the nature of the Sith."
    }, 
    {
        "name": "Bail Prestor Organa", 
        "height": "191", 
        "mass": "unknown", 
        "hair_color": "black", 
        "skin_color": "tan", 
        "eye_color": "brown", 
        "birth_year": "67BBY", 
        "gender": "male", 
        "homeworld": 2, 
        "films": [ 5, 6 ], 
        "species": [ 1 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:53:08.575000Z", 
        "edited": "2014-12-20T21:17:50.463000Z", 
        "image": "bail-organa.jpg",
        "url": 68,
        "description" : "Bail Organa, a member of Alderaan's royal family and the planet's representative to the Republic Senate, earned respect on Coruscant for his honesty and his commitment to justice. Prior to the Clone Wars, Bail served alongside Senator Padmé Amidala as a member of Chancellor Palpatine's Loyalist Committee. The two became close friends, and recruited like-minded allies to prevent Palpatine's alarming grabs for power. At the end of the war, Bail Organa adopted Padmé's daughter Leia and raised her as an Alderaanian princess"
    }, 
    {
        "name": "Jango Fett", 
        "height": "183", 
        "mass": "79", 
        "hair_color": "black", 
        "skin_color": "tan", 
        "eye_color": "brown", 
        "birth_year": "66BBY", 
        "gender": "male", 
        "homeworld": 53, 
        "films": [ 5 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T16:54:41.620000Z", 
        "edited": "2014-12-20T21:17:50.465000Z", 
        "image": "jango-fett.jpg",
        "url": 69,
        "description" : "In the final years of the Republic, Jango Fett was regarded as the best bounty hunter in the galaxy. A proficient marksman and unarmed combatant, Fett was covered in a sleek armored suit that concealed his scarred face. His combat gear featured an arsenal of weaponry, including retractable wrist blades, a snare, dual blaster pistols and other more exotic tools of the trade. In combat, Jango used his harnessed jetpack to gain the advantage of speed and height over his enemies. The backpack also carried a nasty surprise -- an explosive rocket could be launched from it. For interstellar travel, Jango traveled aboard his well-worn starship, Slave I."
    }, 
    {
        "name": "Zam Wesell", 
        "height": "168", 
        "mass": "55", 
        "hair_color": "blonde", 
        "skin_color": "fair, green, yellow", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 54, 
        "films": [ 5 ], 
        "species": [ 30 ], 
        "vehicles": [ 45 ], 
        "starships": [], 
        "created": "2014-12-20T16:57:44.471000Z", 
        "edited": "2014-12-20T21:17:50.468000Z", 
        "image": "zam-wesell.jpg",
        "url": 70,
        "description" : "A shape-shifting Clawdite assassin from Zolan, Zam Wesell could assume any humanoid form. Jango Fett hired her to kill Padmé Amidala on Coruscant, but the Naboo Senator eluded an explosive that destroyed her starship, then escaped poisonous kouhuns let loose in her apartment. Anakin Skywalker and Obi-Wan Kenobi pursued Zam across Coruscant, catching her in the Outlander Club. Before she could talk, Jango shot her dead with a Kaminoan saberdart."
    }, 
    {
        "name": "Dexter Jettster", 
        "height": "198", 
        "mass": "102", 
        "hair_color": "none", 
        "skin_color": "brown", 
        "eye_color": "yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 55, 
        "films": [ 5 ], 
        "species": [ 31 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:28:27.248000Z", 
        "edited": "2014-12-20T21:17:50.470000Z", 
        "image": "dexter-jettster.jpg",
        "url": 71,
        "description" : "Obi-Wan Kenobi counted on Dexter Jettster, an old friend, to identify a poison dart, and Jettster didn't fail him. The cook correctly recognized the small-tined projectile as a Kamino saberdart. Few have ever heard of the planet Kamino, but Dex not only informed Obi-Wan as to its location (12 parsecs south of the Rishi Maze), but also its inhabitants. Dex warned that the native Kaminoans -- cloners of some repute -- keep to themselves, but are welcoming to those with the credits to spare."
    },
    {
        "name": "Lama Su", 
        "height": "229", 
        "mass": "88", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 10, 
        "films": [ 5 ], 
        "species": [ 32 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:30:50.416000Z", 
        "edited": "2014-12-20T21:17:50.473000Z", 
        "image": "lama-su.jpg",
        "url": 72,
        "description" : "The lanky Prime Minister of remote Kamino, Lama Su oversaw the creation of the Galactic Republic's first clone armies. That effort gave his storm-swept homeworld influence in the Republic, but also made it a target of the Separatist military. At the dawn of the new Empire, Lama Su remains in power, seeking the clone Omega for a new project."
    }, 
    {
        "name": "Taun We", 
        "height": "213", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 10, 
        "films": [ 5 ], 
        "species": [ 32 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:31:21.195000Z", 
        "edited": "2014-12-20T21:17:50.474000Z", 
        "image": "taun-we.jpg",
        "url": 73,
        "description" : "A beautiful sylph-like Kaminoan, Taun We is the administrative aide to the Prime Minister of Kamino, Lama Su. When Obi-Wan Kenobi arrived at the rain-swept platforms of Tipoca City, he was greeted by the gentle Taun We. Taun We explained that the Kaminoans had long been expecting the arrival of a Jedi envoy, since a Jedi representative, Master Sifo-Dyas, commissioned a clone army a decade earlier. Kenobi bluffed his way into the heart of the cloning operation, and had the naive Taun We introduce him to the original source of the clones, Jango Fett."
    }, 
    {
        "name": "Jocasta Nu", 
        "height": "167", 
        "mass": "unknown", 
        "hair_color": "white", 
        "skin_color": "fair", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 9, 
        "films": [ 5 ], 
        "species": [ 1 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:32:51.996000Z", 
        "edited": "2014-12-20T21:17:50.476000Z", 
        "image": "jocasta-nu.jpg",
        "url": 74,
        "description" : "The Jedi Archives are the galaxy's greatest repository of knowledge, and Madame Jocasta Nu is their Chief Librarian. She helps other Jedi find information in the Archive using its data terminals, and she controls access to the restricted contents of its Holocron Vault. Jocasta Nu can sometimes be too confident in thinking that the Archives contain the correct answers to all questions."
    }, 
    {
        "name": "R4-P17", 
        "height": "96", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "silver, red", 
        "eye_color": "red, blue", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 28, 
        "films": [ 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:43:36.409000Z", 
        "edited": "2014-12-20T21:17:50.478000Z", 
        "image": "r4-p17.jpg",
        "url": 75,
        "description" : "R4-P17 was an astromech droid assigned to Obi-Wan Kenobi, and assisted the Jedi Master on many missions, from Kamino and Geonosis to Teth and Tatooine. She was destroyed during the Battle of Coruscant when buzz droids swarmed Obi-Wan’s fighter, ripping the faithful droid’s dome from her metal body."
    }, 
    {
        "name": "Wat Tambor", 
        "height": "193", 
        "mass": "48", 
        "hair_color": "none", 
        "skin_color": "green, grey", 
        "eye_color": "unknown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 56, 
        "films": [ 5 ], 
        "species": [ 33 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:53:52.607000Z", 
        "edited": "2014-12-20T21:17:50.481000Z", 
        "image": "wat-tambor.jpg",
        "url": 76,
        "description" : "The foreman of the Techno Union, Wat Tambor was one of the original and most fervent Separatist leaders, pledging his loyalty and his battle droid armies to Count Dooku at a pivotal meeting on Geonosis. Later in the war, Tambor was appointed emir of Ryloth. His occupation was a cruel one, in which Tambor stripped the Twi'leks of whatever valuables he could find, then bombed their villages."
    }, 
    {
        "name": "San Hill", 
        "height": "191", 
        "mass": "unknown", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "gold", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 57, 
        "films": [ 5 ], 
        "species": [ 34 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T17:58:17.049000Z", 
        "edited": "2014-12-20T21:17:50.484000Z", 
        "image": "san-hill.jpg",
        "url": 77,
        "description" : "San Hill was a male Muun who was the chairman of the InterGalactic Banking Clan at the onset of the Clone Wars and signed Count Dooku’s treaty. He served as the IG representative on the Separatist Council until he was murdered unceremoniously by the Sith Lord Darth Vader shortly after the end of the war."
    }, 
    {
        "name": "Shaak Ti", 
        "height": "178", 
        "mass": "57", 
        "hair_color": "none", 
        "skin_color": "red, blue, white", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 58, 
        "films": [ 5, 6 ], 
        "species": [ 35 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T18:44:01.103000Z", 
        "edited": "2014-12-20T21:17:50.486000Z", 
        "image": "shaak-ti.png",
        "url": 78,
        "description" : "A wise and patient Jedi Master, the Togruta Shaak Ti fought at the Battle of Geonosis, and supervised the training of clone cadets on Kamino. There, she struggled to balance the necessity of producing capable troopers with compassion for the clones as living beings. Ti helped defend Kamino against Separatist attack, balancing assignments in the field with her duties on the Jedi Council."
    }, 
    {
        "name": "Grievous", 
        "height": "216", 
        "mass": "159", 
        "hair_color": "none", 
        "skin_color": "brown, white", 
        "eye_color": "green, yellow", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 59, 
        "films": [ 6 ], 
        "species": [ 36 ], 
        "vehicles": [ 60 ], 
        "starships": [ 74 ], 
        "created": "2014-12-20T19:43:53.348000Z", 
        "edited": "2014-12-20T21:17:50.488000Z", 
        "image": "grievous.jpg",
        "url": 79,
        "description" : "General Grievous was a brilliant Separatist military strategist and a feared Jedi hunter, known for his ruthlessness and hacking cough. His body itself was a weapon, allowing him lightning quick strikes and devastating blows. But he was also quick to run from a fight, a tactic that worked until one final meeting with Obi-Wan Kenobi."
    }, 
    {
        "name": "Tarfful", 
        "height": "234", 
        "mass": "136", 
        "hair_color": "brown", 
        "skin_color": "brown", 
        "eye_color": "blue", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 14, 
        "films": [ 6 ], 
        "species": [ 3 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T19:46:34.209000Z", 
        "edited": "2014-12-20T21:17:50.491000Z", 
        "image": "tarfful.jpg",
        "url": 80,
        "description" : "A massive Wookiee general, Tarfful helped defend his native Kashyyyk during the Clone Wars. A distress signal brought Tarfful and his most trusted warriors rushing to Chewbacca's help against the hated Trandoshans on the hunting grounds of Wasskah. Later, Tarfful and Chewbacca fought side by side with General Yoda on the battlegrounds of Kashyyyk."
    }, 
    {
        "name": "Raymus Antilles", 
        "height": "188", 
        "mass": "79", 
        "hair_color": "brown", 
        "skin_color": "light", 
        "eye_color": "brown", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 2, 
        "films": [ 1, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T19:49:35.583000Z", 
        "edited": "2014-12-20T21:17:50.493000Z", 
        "image": "raymus-antilles.png",
        "url": 81,
        "description" : "A level-headed ship officer schooled in diplomacy, and a capable pilot entrusted to ferry about the royal family of Alderaan, Captain Antilles served in Bail Organa's command staff. He was part of the bridge crew of Organa's diplomatic cruiser, a role he would continue during the time Princess Leia served as Senator of Alderaan."
    },
    {
        "name": "Sly Moore", 
        "height": "178", 
        "mass": "48", 
        "hair_color": "none", 
        "skin_color": "pale", 
        "eye_color": "white", 
        "birth_year": "unknown", 
        "gender": "female", 
        "homeworld": 60, 
        "films": [ 5, 6 ], 
        "species": [], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T20:18:37.619000Z", 
        "edited": "2014-12-20T21:17:50.496000Z", 
        "image": null,
        "url": 82,
        "description" : "A pale Umbaran, Sly Moore served as Palpatine’s senior administrative aide during his chancellorship, attending to countless affairs of state. Moore’s enigmatic silence made her the object of considerable curiosity on Coruscant, with rumors abounding about her past and mysterious abilities she supposedly possessed."
    }, 
    {
        "name": "Tion Medon", 
        "height": "206", 
        "mass": "80", 
        "hair_color": "none", 
        "skin_color": "grey", 
        "eye_color": "black", 
        "birth_year": "unknown", 
        "gender": "male", 
        "homeworld": 12, 
        "films": [ 6 ], 
        "species": [ 37 ], 
        "vehicles": [], 
        "starships": [], 
        "created": "2014-12-20T20:35:04.260000Z", 
        "edited": "2014-12-20T21:17:50.498000Z", 
        "image": null,
        "url": 83,
        "description" : "Greeting Obi-Wan Kenobi during his search for General Grievous on windswept Utapau was Port Administrator Tion Medon. The tall, gaunt Utapaun initially feigned ignorance about Grievous' whereabouts, but then whispered a warning to Kenobi. Grievous was indeed on the planet, hiding on the tenth level of the sinkhole city with an army of thousands of battle droids."
    }
]];

module.exports = characterSeeder;